### ISSUE TITLE
Set up a website for proophessor and split documentation

### ISSUE THREAD

**Issue by codeliner** [prooph/proophessor#18]
We can use [couscous](http://couscous.io/docs/getting-started.html) to create a website from markdown files included in the repo.

Goal of this ticket is to split current documention into several markdown files and create website from them with couscous. The website should improve readability of the docs and ease navigation.

**Comment by codeliner** [comment]
We should have a look at bookdown too. Zend is also evaluating it. See https://github.com/zendframework/zend-diactoros/pull/25

**Comment by weierophinney** [comment]
I'm evaluating bookdown because it was written to solve the exact problem we have: being able to compile docs from multiple repositories into a single manual. When I was evaluating couscous, I was already getting headaches trying to figure out how I'd make that happen. If all your docs are in one place, though, either one would work fantastically.

**Comment by codeliner** [comment]
@weierophinney Many thanks for your input. I need the same feature (compile docs from multiple repos) and had a similar feeling while looking at couscous.

**Comment by codeliner** [comment]
Closing as we use bookdown since some time now and are happy with it.
